global:
  scrape_interval: 5s

scrape_configs:

  # ========================
  # SPRING BOOT MICROSERVICES
  # ========================

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8081"]

  - job_name: "ingestion-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ingestion-service:8080"]

  - job_name: "historical-temp-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["historical-temp-service:8084"]

  # ========================
  # RABBITMQ (PLUGIN NATIVO)
  # ========================

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]