global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["api-gateway:8081"]

  - job_name: "ingestion-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["ingestion-service:8080"]

  - job_name: "alert-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["alert-service:8080"]

  - job_name: "historical-temp-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["historical-temp-service:8084"]