server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: ingestion-service
          uri: http://ingestion-service:8080
          predicates:
            - Path=/ingestion/**
          filters:
            - StripPrefix=1

        - id: actuator-direct
          uri: http://ingestion-service:8080
          predicates:
            - Path=/actuator/**

        - id: alert-service
          uri: http://alert-service:8083
          predicates:
            - Path=/alerts/**
          filters:
            - StripPrefix=1

        - id: historical-temp-service
          uri: http://historical-temp-service:8084
          predicates:
            - Path=/historical/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus