server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: ingestion-service
          uri: http://localhost:8080
          predicates:
            - Path=/ingestion/**
          filters:
            - StripPrefix=1
            
        - id: actuator-direct
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/**

        - id: alert-service
          uri: http://localhost:8083
          predicates:
            - Path=/alerts/**
          filters:
            - StripPrefix=1
        
