spring.application.name=ingestion-service

# Porta da aplicação
server.port=8080

# RabbitMQ (Docker)
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# PostgreSQL (Docker)
spring.datasource.url=jdbc:postgresql://postgres-db:5432/sensordb
spring.datasource.username=admin
spring.datasource.password=admin

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,prometheus


management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Logging
logging.file.name=logs/app.log